[package]
name = "mod-oud"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12"
tokio = { version = "1.0", features = ["full"] }
poise = "0.6"
dotenvy = "0.15"
sqlx = { version = "0.9.0", features = ["postgres", "chrono", "runtime-tokio", "uuid", "json"] }
duration-str = "0.21.0"
chrono = { version = "0.4.45", features = ["serde"] }
futures = "0.3.33"
serde = { version = "1.0.229", features = ["derive"] }
rustrict = "0.7.38"
regex = "1.13.1"
linkify = "0.11.0"
serde_json = "1.0.151"
prost = "0.14.4"
reqwest = { version = "0.12", features = ["json"] }
fred = { version = "10.1.0", features = ["partial-tracing", "enable-rustls", "i-scripts", "subscriber-client"] }
rand = "0.10.2"
axum = { version = "0.8", features = ["macros", "ws"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tower-http = { version = "0.7.0", features = ["cors", "trace"] }
unicode-segmentation = "1.10.1"
serde_with = "3.21.0"
futures-util = "0.3.33"
moka = { version = "0.12", features = ["future"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.24.0", features = ["v4", "serde"] }
emojis = "0.9.0"
sysinfo = "0.39.6"
anyhow = "1.0.104"
hmac = "0.13.0"
sha2 = "0.11.0"
hex = "0.4.3"
humantime = "2.1"
alloy-primitives = "1.6.1"
bitcoin = "0.33.0-beta"
bs58 = "0.5.1"
base64 = "0.23.0"
serde_path_to_error = "0.1.20"
resvg = "0.48.1"
image = { version = "0.25.10", features = ["webp", "png", "jpeg"] }
unit-prefix = "0.5.2"
chrono-tz = "0.10.4"
songbird = { version = "0.6.0", features = [] }
symphonia = { version = "0.5.0", features = ["all"] }
async-trait = "0.1.89"
aho-corasick = "1.1.5"
scraper = "0.27.0"
subtle = "2.6.1"

[lints.rust]
missing_docs = "deny"

[lints.rustdoc]
all = "deny"

[lints.clippy]
struct_excessive_bools = "allow"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
# unwrap_used = "warn"

# missing_errors_doc = "deny"
# missing_panics_doc = "deny"
# missing_safety_doc = "deny"
