CREATE TABLE IF NOT EXISTS warns (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    moderator_id BIGINT NOT NULL,
    reason VARCHAR(1000) DEFAULT 'No reason provided',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);